importPackage(
	java.lang, java.io,java.nio,
	java.util,
	java.net,
	java.util.concurrent,
	java.sql,
	java.nio.charset,
	java.text,
	java.util.concurrent.atomic,
	java.util.regex,
	java.util.Map);

importPackage(com.bmtech,
	com.bmtech.utils,
	com.bmtech.utils.bmfs,
	com.bmtech.utils.bmfs.tool,
	com.bmtech.utils.bmfs.util,
	com.bmtech.utils.c2j,
	com.bmtech.utils.c2j.cTypes,
	com.bmtech.utils.charDet,
	com.bmtech.utils.counter,
	com.bmtech.utils.http,
	com.bmtech.utils.http.fileDump,
	com.bmtech.utils.http.itrCrawl,
	com.bmtech.utils.io,
	com.bmtech.utils.io.diskMerge,
	com.bmtech.utils.log,
	com.bmtech.utils.rds,
	com.bmtech.utils.rds.convert,
	com.bmtech.utils.ruledSegment,
	com.bmtech.utils.ruledSegment.affix,
	com.bmtech.utils.security,
	com.bmtech.utils.segment,
	com.bmtech.utils.superTrimer,
	com.bmtech.utils.systemWatcher,
	com.bmtech.utils.systemWatcher.innerAction,
	com.bmtech.utils.tcp);

var ByteArray = Java.type("byte[]");
var IntArray = Java.type("int[]");